# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reserver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='isAvailable',
            new_name='canRent',
        ),
        migrations.AddField(
            model_name='flat',
            name='reservedDate',
            field=models.ManyToManyField(to='Reserver.Reserved'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reserver.Town'),
        ),
        migrations.AlterField(
            model_name='reserved',
            name='flatName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reserver.Flat'),
        ),
    ]
