# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserver', '0003_remove_flat_canrent'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='canRent',
            field=models.BooleanField(default=False),
        ),
    ]
