# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reserver', '0004_flat_canrent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='location',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='reservedDate',
        ),
        migrations.RemoveField(
            model_name='reserved',
            name='flatName',
        ),
    ]
