# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reserver', '0005_auto_20170530_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Reserver.Town'),
        ),
        migrations.AddField(
            model_name='flat',
            name='reservedDate',
            field=models.ManyToManyField(to='Reserver.Reserved'),
        ),
        migrations.AddField(
            model_name='reserved',
            name='flatName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Reserver.Flat'),
        ),
    ]
