# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reserver', '0007_auto_20170530_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='location',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='reservedDate',
        ),
        migrations.RemoveField(
            model_name='reserved',
            name='flatName',
        ),
        migrations.DeleteModel(
            name='Flat',
        ),
        migrations.DeleteModel(
            name='Reserved',
        ),
        migrations.DeleteModel(
            name='Town',
        ),
    ]
