# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reserver', '0009_auto_20170530_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='reservedDate',
        ),
    ]
